### ISSUE TITLE
"binary tree" is different from "binary search"

### ISSUE THREAD

**Issue by cakoose** [hieunc229/copilot-clone#1]
The GIF in your ReadMe and on Product Hunt shows the user searching for "binary tree" but getting results for array-based binary _search_, which is not the same thing.

You might want to change the GIF to a more successful example.  Unless you're intentionally trying to highlight the tool's shortcomings, in which case I'm impressed with your honesty!

**Comment by hieunc229** [comment]
Hi @cakoose, the extension is indeed sometimes like that. I was focusing more on the presentation and forgot about the context. I'll update it

Thanks for spotting it
