### ISSUE TITLE
Publish extension to Open VSX Registry.

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#11]

**Comment by hieunc229** [comment]
Interesting. I'll check out this Open VSX Registry now. If it takes a bit works, I might have to do it abit later

**Comment by clin1234** [comment]
Instructions here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by hieunc229** [comment]
Cool, I'm publishing it.

**Comment by clin1234** [comment]
Github action: https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by hieunc229** [comment]
_Update: the extension is now available here https://open-vsx.org/extension/captain-stack/captain-stack_

---

I've published it. I'll need to claim the `namespace` and realized you're claiming `cpt_stack` earlier. I got the `captain-stack` namespace, you can remove the `cpt_stack`

About the published extension, I might need to change `copilot-clone` to `captain-stack` too. And will publish changes for the future updates

**Comment by clin1234** [comment]
#15

**Comment by hieunc229** [comment]
Hey @clin1234, even though the `inlineSuggest` configuration is available. It's still not available yet. Below is the error message when using VSCode and VSCodium in normal mode

![Screen Shot 2021-07-25 at 9 02 49 am](https://user-images.githubusercontent.com/8464869/126885240-1a712d7c-8fe4-4e84-b4c2-97475d81d881.png)

To use `inlineSuggest` in VSCode stable version, you need to run `code --enable-proposed-api` in Terminal for MacOS or the alternative in other OS. I don't know how to enable it in VSCodium yet.

The point is, it is still troublesome for the end-user to install this plugin. Let's keep it in development for now and wait until it is officially supported

**Comment by Kek5chen** [comment]
> The point is, it is still troublesome for the end-user to install this plugin. Let's keep it in development for now and wait until it is officially supported

I agree. This mostly because, as we already have seen. Stuff may change in future releases of VSCode using inline-suggestions. Things might not be supported, or they may drop support completely, unlikely but not impossible.

This thread will therefore be paused until inline-suggestions have officially released, this probably with GitHub Copilot.
