### ISSUE TITLE
Error when attempting to publish extension to Open VSX

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#12]
When adding the Github Actions to publish the extension to Open VSX, [here](https://github.com/clin1234/copilot-clone/blob/master/.github/workflows/publish.yml), I received the following error.

Error: SVGs are restricted in README.md; please use other file image formats, such as PNG: https://github.com/Microsoft/vscode-extension-samples/raw/HEAD/./logo.svg

**Comment by hieunc229** [comment]
On the error, I can see the repository path is incorrect. 

Though, I had the same error when trying to publish with the CLI. After removing the SVG, it will complain about not being able to find `.png` files.

I'll have a look and publish it to Open VSX today

**Comment by clin1234** [comment]
See #13
