### ISSUE TITLE
Clarify supported Node versions in Readme

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#18]
@hieunc229, do you intend to support not only the 14 branch, but also the 12 branch as well

**Comment by hieunc229** [comment]
Do you have any trouble running with Node 12.x.x? 

I ran with Node 12.x.x and there was no problem

**Comment by clin1234** [comment]
No, just clarifying if you intend to support Node 12 with the extension.

**Comment by clin1234** [comment]
Never mind: https://github.com/Microsoft/vscode/issues/18253#issuecomment-271235914

**Comment by hieunc229** [comment]
I'd appreciate you double-check before discussing it.
