### ISSUE TITLE
Activating extension failed

### ISSUE THREAD

**Issue by kumarangithub6485** [hieunc229/copilot-clone#2]
I am getting the below issue while installing this extension:
`"Activating extension 'hieunc229.copilot-clone' failed: Cannot find module 'c:\Users\userid\copilot-clone-1\out\extension.js' Require stack: - c:\Users\userid\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js - c:\Users\userid\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js - c:\Users\userid\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js.`

please help to resolve

**Comment by hieunc229** [comment]
Hi @kumarangithub6485, seem like it's missing the compiled code. 

Have you:
- Install dependencies (use the command `npm install` or `yarn`)?

**Comment by kumarangithub6485** [comment]
I installed npm but not installed Yarn..

**Comment by hieunc229** [comment]
If you have already had npm, then you can:

1. Navigate to the root folder of the project
2. On VSCode terminal, run `npm install`. This will automatically install the project dependencies

You can check out this video, step by step install, and start playing with Captain Stack https://youtu.be/PAAG1zlVeZM?t=180

Let me know if you still have trouble setting it up

**Comment by kumarangithub6485** [comment]
Hi,

I installed it and went straight to the root folder. I'm still getting the same error message.
Is it possible for someone to call me and provide assistance in resolving this problem? 

As per Video, I have checked everything, still shows the same issue.

**Comment by hieunc229** [comment]
For sure.

Can you email me at hieunc@inverr.com, or DM on Twitter @hieuSSR? I can have a look

**Comment by kumarangithub6485** [comment]
On Twitter, I have DM. Please help me because your technology appears fantastic and I'd like to learn more about it.

**Comment by kumarangithub6485** [comment]
Thank you Nguyen for quickly fixing the issue. Now it works..

**Comment by Manuel-Suarez-Abascal** [comment]
@kumarangithub6485 I have the exact same problem. How did you solve it?

**Comment by hieunc229** [comment]
I'll close this issue. In case you run into the same problem, that means you have not installed dependencies.

Make sure you have installed:
- VSCode Insider
- Nodejs
- Either NPM or Yarn for dependencies management

Then:
1. Navigate to the root folder of the project
2. On VSCode terminal, run npm install (_this will automatically install the project dependencies_)
3. Start debugging (using `F5`, or on the menu, choose `Run > Start Debugging`). 
4. A new VSCode windows will appear, you can start using Captain Stack on these windows

Feel free to open a new thread if you have any issue
