### ISSUE TITLE
I can seem to get it to work

### ISSUE THREAD

**Issue by lindamacdonald** [hieunc229/copilot-clone#3]

**Comment by lindamacdonald** [comment]
Hey there :) I found Captain stack on ProductHunt so of course had to give it a whirl immediately.  But I cannot seem to get it to run. I downloaded and installed vs code insider and then I downloaded the folder from the repo and ran npm install and did some test runs with some simple buggy code in react.js and went to the debug tab, but nothing much is happening...

**Comment by hieunc229** [comment]
Hi Lina, thanks for checking it out.

I realized the instruction might be a bit unclear, just want to make sure (in order):

1. After installing the dependencies (which you did), did you open the extension directory with VSCode Insider?
2. From VSCode Insider's top toolbar, choose `Run > Start Debugging`
3. Now, it will open a new VSCode window. You can only try the code completion feature on this window

If you still have a problem, I could have a have look using TeamViewer (could you send me an email to hieunc@inverr.com, or twitter https://twitter.com/hieuSSR)

**Comment by lindamacdonald** [comment]
Hey there thanks a mil for getting back to me so quickly :) so when I have run npm install and go to run > start debugging it doesnt start a new window, it gives me the option of choosing:
chrome
edge
node.js
node.js legacy and vs code extensions

do I choose one of these options or perhaps I am missing something? This is a completely fresh install of vs code insider so perhaps I should switch on something before running the debugging?

**Comment by hieunc229** [comment]
No worries.

I'm not entirely sure, what you described hasn't happened to me before. I guess you should choose the last option `node.js legacy and vs code extensions`. Let me know how it goes.

_Also, it might be easier if I could have a look_

**Comment by lindamacdonald** [comment]
Hang on will create a screencast for you to take a look because a screenshot cannot capture the drop down :)

**Comment by hieunc229** [comment]
Sure, that'd be great!

**Comment by lindamacdonald** [comment]
so sorry for the typos hihi :) but here it is, hope the quality is ok and if you need me to do it again I will :)
https://www.awesomescreenshot.com/video/4382250?key=31b11bc5bebd23542b299111adc698db

**Comment by hieunc229** [comment]
I make typos so often too, argg. 

Thanks for the screencast. I think the problem was on your VSCode Insider, the root folder was not `copilot-clone-master`, but was its parent. 

Can you try to open `copilot-clone-master` as the root folder? (_you can drag the folder to VSCode Insider to open_)

**Comment by lindamacdonald** [comment]
ok cloned the repo so there would be no parent folder to deal with but still the same so will tinker on with it and let you know when it is working thanks a mil for helping...is there any chance that you will release it to the vs marketplace so I can just push and install? :)

**Comment by hieunc229** [comment]
I will publish the extension to the marketplace. But the VSCode inline-completion feature is still experimental so I can't push it to the marketplace yet. I'm not sure when will it be ready either.

About the issue, when cloning, you should specify the target folder is the current folder (use a dot)

_For example: note that there is the dot at the end_

```ssh
$ git clone https://github.com/hieunc229/copilot-clone.git .
```

**Comment by hieunc229** [comment]
I'm pretty sure the problem was the root folder of VSCode Insider wasn't correct. It's the one you see on the left panel (not the Terminal). When I have the incorrect root folder, it showed as you described (choose an option between: `chrome, edge, nodejs, ...`

I've just published a video, shows how to install. There was a change I made recently, so I didn't have to install dependencies in this video.

The video is available here https://youtu.be/MD-kzsF0Scg

**Comment by nokiz** [comment]
Hello. I was having the same issue and I solved it restarting windows after installing VS Code Insider.

**Comment by DevHunvee3** [comment]
@hieunc229 I'm on windows 10 and when I follow your video (I run npm start btw), and start the debugger, I get the new VSCode Insiders window but I also get an "unsupported" notification and obviously the extension doesn't work.

https://user-images.githubusercontent.com/26755663/125291307-9e907980-e2f7-11eb-8311-f21d6849ebf6.mp4

**Comment by Kek5chen** [comment]
> @hieunc229 I'm on windows 10 and when I follow your video (I run npm start btw), and start the debugger, I get the new VSCode Insiders window but I also get an "unsupported" notification and obviously the extension doesn't work.

Same thing here

**Comment by hieunc229** [comment]
Hey @DevHunvee3, your installation seems correct. I'm not entirely sure what happened. 

I sent you an email, if I could use Teamviewer to inspect, that'd be great!

**Comment by hieunc229** [comment]
Hey @DevHunvee3 @Kek5chen, I'm moving your question into a new thread 
- [Showing "unsupported" when running Captain Stack #4](https://github.com/hieunc229/copilot-clone/issues/4)
