### ISSUE TITLE
Add GH page.

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#30]
For greater public visibility, I think we should add a GH page in a separate branch. See https://clin1234.github.io/copilot-clone as reference.

**Comment by hieunc229** [comment]
Hey Charlie, I thought about setting up a website. Though I don't think it's necessary at the moment. 

There's not much content to show except repeating what's already in the main GH repository

Btw, @Kek5chen is cooking up a user guide, help people resolving basic problem. I think if he publish it, that'd be helpful

**Comment by hieunc229** [comment]
I'll close this thread for now. Feel free to reopen or create a new one for further discussion
