### ISSUE TITLE
Use out of the debug environment

### ISSUE THREAD

**Issue by Huzukawaiii** [hieunc229/copilot-clone#33]
I cant use the extension in VSCode Insider without the debug environment.

Extension is enable and work except in normal mode.

http://cdn.haxxme.fr/404687c8-37de-4bbd-8c31-2bc8e7c75a42.png

**Comment by hieunc229** [comment]
As mentioned in the [README](https://github.com/hieunc229/copilot-clone/blob/master/README.md):

_⚠️ This extension uses a proposed API (inline-completion) and can only be used for extension development in the VSCode Insider release. It's not yet available on VSCode_

I can't publish the extension yet, though I think it will available soon

**Comment by hieunc229** [comment]
I'll close this thread. Feel free to reopen or create another thread for further discussion
