### ISSUE TITLE
Load results from sources upon changing settings without reloading window.

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#34]
With `captainStack.settings.sites`, is there some way such that after toggling which sites to enable or disable, these changes would occur immediately after the next search query without having to reload the window?

**Comment by hieunc229** [comment]
When VSCode started, Captain Stack loads the `config`. I didn't want VSCode to load the config every time the search function is called, which can be a lot. 

Though, it can be done by moving the config into the `isEnabled` function in the [ExtractorAbstract.ts#L13](https://github.com/hieunc229/copilot-clone/blob/master/src/utils/extractors/ExtractorAbstract.ts#L13)

**Comment by hieunc229** [comment]
This issue is fixed in #37
