### ISSUE TITLE
Buffer() is deprecated 

### ISSUE THREAD

**Issue by aamir1705** [hieunc229/copilot-clone#38]
(node:4223) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code-insiders --trace-deprecation ...` to show where the warning was created)
![2021-08-23-142745_1920x1080_scrot](https://user-images.githubusercontent.com/7711419/130451051-d1c81416-5515-4568-a285-a24f40907ca4.png)

**Comment by hieunc229** [comment]
I don't think we have control over it. You can ignore the warning

**Comment by hieunc229** [comment]
Close due to inactivities

**Comment by mrdm92** [comment]
but I can't use Captain Stack.

**Comment by hieunc229** [comment]
> but I can't use Captain Stack.

That's definitely not the issue.

- Have you follow the installation steps?
- Have you enable inline suggestions?
