### ISSUE TITLE
Remove generated JS files from repo

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#39]
Since the TS files are compiled every time `npm install` is run and after any modification to them, would it not make sense to include only TS files for development?

**Comment by hieunc229** [comment]
The extension used to have no dependencies and was able to run without `npm install`. I wanted to ship the generated JS files without the TS sources. 

It's impossible now and makes sense not to include the generated JS files in the repo.

**Comment by hieunc229** [comment]
Close due to inactivity
