### ISSUE TITLE
Showing "unsupported" when running Captain Stack 

### ISSUE THREAD

**Issue by hieunc229** [hieunc229/copilot-clone#4]
**I'm moving this issue into a new thread since it isn't related to the old one**

@hieunc229 I'm on windows 10 and when I follow your video (I run npm start btw), and start the debugger, I get the new VSCode Insiders window but I also get an "unsupported" notification and obviously the extension doesn't work.

https://user-images.githubusercontent.com/26755663/125291307-9e907980-e2f7-11eb-8311-f21d6849ebf6.mp4

_Originally posted by @DevHunvee3 in https://github.com/hieunc229/copilot-clone/issues/3#issuecomment-878257435_

**Comment by hieunc229** [comment]
Hey @DevHunvee3, your installation seems correct. I'm not entirely sure what happened.
I sent you an email, if I could use Teamviewer to inspect, that'd be great!

**Comment by Kek5chen** [comment]
I would be up for showing you what is happening in team viewer too

**Comment by hieunc229** [comment]
Thanks, @Kek5chen that'd be awesome. How can I contact you? email/twitter?

**Comment by Kek5chen** [comment]
Using discord for screen sharing and communication would be very appreciated.

**Comment by hieunc229** [comment]
Great idea. I've just set up a discord channel here https://discord.gg/DTHTaQJg

**Comment by hieunc229** [comment]
Thanks @Kek5chen for helping to resolve the problem. Turn out the new version VSCode Insider v.1.59 will show an "unsupported" error.

But the extension still works (just ignore the error)

**Comment by DevHunvee3** [comment]
@hieunc229 Sorry for replying late, even though I ignore the error, it still doesn't work, as shown in the video, I wrote the same example you did, including the final dot and no suggestions appeared. Unfortunately I can't grant you access right now since i'm on my work computer.

**Comment by hieunc229** [comment]
Alright. I think the problem was the space character in your syntax. It starts with `//find` (no space) and end with a dot `.`

```js
//find {find key word}.
```

**Comment by DevHunvee3** [comment]
tried it but still nothing... let me try install it again

**Comment by Kek5chen** [comment]
To solve this issue once and for all:

The issue is not present in an ealier stage of the Visual Studio Code Insider releases. They changed how the inline autocompletion feature works in 1.59.

A fix for now is to download [Version 1.58 from chocolatey](https://community.chocolatey.org/packages/vscode-insiders/1.58.0.20210707) until the code has been adapted to the changes of Version 1.59.

As far as development with this extension goes just use this approach for now and wait for an update of the repo.

Best Regards,
kek5chen

**Comment by hieunc229** [comment]
Thanks @Kek5chen.

Actually, on v1.59, it showed the "unsupported" error but things still work. Not sure where's the error coming from but you can ignore it

**Comment by Kek5chen** [comment]
Resolved in merge #5
