### ISSUE TITLE
Coding Language support

### ISSUE THREAD

**Issue by FeelsBadMan1** [hieunc229/copilot-clone#40]
hello, i would like to use in python using Pycharm IDE. Im not sure if that is already possible but if not than please implement it ;D

**Comment by hieunc229** [comment]
Hi there, I've tried to create a Intellij plugin (asumming Pycharm is similar) and haven't figure it out yet.

I'm having a few things to focus on so can't working Intellij at the moment. If you like to work on it, let me know

**Comment by hieunc229** [comment]
Close due to inactivity
