### ISSUE TITLE
buffer error

### ISSUE THREAD

**Issue by mrdm92** [hieunc229/copilot-clone#41]
Hi. When I choose Run > Start Debugging from the top menu, this error will appear in the debug console:
(node:8444) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created)

**Comment by hieunc229** [comment]
Duplicate of https://github.com/hieunc229/copilot-clone/issues/38

Hi, you can ignore this. It's a warning outside of Captain Stack (hopefully VSCode will update soon)

**Comment by hieunc229** [comment]
I'll close this thread as it is not an issue within Captain Stack's scope
