### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by TarunavBA** [hieunc229/copilot-clone#44]
Please make it available on Vscode stable version also!

**Comment by hieunc229** [comment]
Welcome, @TarunavBA. 

This extension uses a proposed API and the VSCode Marketplace doesn't accept extensions with the proposed API just yet. I'll publish once it is possible

**Comment by TarunavBA** [comment]
Ok thanks. Hey also can you help me in my python project or do you know
anyone who can help? If you know please share their email id to
***@***.***

~ 🤖

**Comment by hieunc229** [comment]
Close this thread as it has been resolved and having unrelated discussion
