### ISSUE TITLE
Certificate expired error

### ISSUE THREAD

**Issue by avangersGameDestruction** [hieunc229/copilot-clone#45]
FetchError: request to https://stackoverflow.com/questions/53355882/how-do-i-write-a-javascript-function-that-prints-hello-world-every-3rd-time-it failed, reason: certificate has expired

i got this with everything maybe your able to update it and find the debug or scanning isseu

**Comment by avangersGameDestruction** [comment]
btw this was a example of other ways that i just got unlucky or made a mistake but it is on every search comment i got this

**Comment by hieunc229** [comment]
Hi Dutchy, I believe this issue is caused by expired certificates packed with VSCode. Looks like we need to wait for the next VSCode release to fix the issue (hopefully)

Though, a quick fix could be insert `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` into line no 2 in `src/utils/fetchPageContent.ts` file

Hope it helps

**Comment by avangersGameDestruction** [comment]
sorry to say it didn't solve the expired error like you said we probably need to wait till vscode got a new release for now we need to wait i did try the source code on vs insiders and vscode ( newest version ) everything works fine except the part where we write //find javascript binary. it is expired and my console gave me the followed message

node:15956) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)

[INFO] [auth] [2021-10-03T17:02:42.275Z] Invalid copilot token: missing token

resources\app\out\bootstrap-fork.js:5

just to inform you the error maybe this helps i just saw it now to find a solution if not no problem your hard work got respected and we will wait on a new version of vs code or when a new update happen of you or the others who help you solving creating and updating on this wonderful alternative version of github copilot

**Comment by avangersGameDestruction** [comment]
expired session fix :
location out/fetchpagecontent.js


code who need to be placed there 
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fetchPageTextContent = void 0;
// test by myself
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
const node_fetch_1 = require("node-fetch");
function fetchPageTextContent(url) {
    return new Promise((resolve, reject) => {
        return node_fetch_1.default(url)
            .then(rs => rs.text())
            .then(textContent => resolve({ textContent, url }))
            .catch(reject);
    });
}
exports.fetchPageTextContent = fetchPageTextContent;

**Comment by hieunc229** [comment]
> [INFO] [auth] [2021-10-03T17:02:42.275Z] Invalid copilot token: missing token

This is not Captain Stack error, but Github Copilot. You'll need to disable Github Copilot for this error

> expired session fix :
location out/fetchpagecontent.js

Whatever you change in the output files (any files in the `out` directory) will be remove when `Start Debugging`. Make sure you edit the file from `src` directory.

**Comment by hieunc229** [comment]
Please use this solution for a quick fix https://github.com/hieunc229/copilot-clone/issues/45#issuecomment-932954789
