### ISSUE TITLE
Feature request: Support for other editors (JetBrains, Visual Studio, Emacs).

### ISSUE THREAD

**Issue by RashiqAzhan** [hieunc229/copilot-clone#47]
Is this possible? Especially for the JetBrains line of products?

**Comment by hieunc229** [comment]
Welcome Rashiq, as I mentioned in https://github.com/hieunc229/copilot-clone/issues/40#issuecomment-912895508.

I'm unfamiliar with those code editor, and have a few things need to focus on at the moment. If you like to work on it, I'd happy to work with you

**Comment by Kek5chen** [comment]
I also code using JetBrains products exclusively. Though for the same reason as that GitHub Copilot was only made for VSCode and JetBrains products, I don't think that we will be adding support for the JetBrains products stack any time soon.

I think your best bet would be to just sign up for the GitHub Copilot waitlist, which you probably have around the time you opened this issue and most likely already have access to Copilot for JetBrains.

**Comment by hieunc229** [comment]
Close since there is no plan to support other editors
