### ISSUE TITLE
Property 'setStatusBarMessage' does not exist on type 'typeof window'

### ISSUE THREAD

**Issue by Srivathsav-max** [hieunc229/copilot-clone#48]
error TS2339: Property 'setStatusBarMessage' does not exist on type 'typeof window'.

67     vscode.window.setStatusBarMessage(`CaptainStack: Start loading snippet results...`, promise);

**Comment by hieunc229** [comment]
Welcome @Srivathsav-max. This is unlikely a problem if everything was setup correctly.

**Comment by asim1425** [comment]
Try This: (Work For Me)
npm install
Then npm install vscode
Then Ctrl + Shift + P And Select ( Developer: Reload Window )
( Sorry For Bad English )

**Comment by Srivathsav-max** [comment]
Thank you it helped me a lot
