### ISSUE TITLE
Errors after start debuging

### ISSUE THREAD

**Issue by Fabbboy** [hieunc229/copilot-clone#49]
Everytime i start the programm i get this errors:

The property  "setStatusBarMessage " does not exist for the type "typeof window "
And
many others like getText, Range, showerrormessage, ""vscode""

how to fix this?

**Comment by Fabbboy** [comment]
I installed "vscode" with npm install now i have this problem: 

error:FetchError: request to https://stackoverflow.com/questions/38340775/php-and-league-of-legends-api-how-to-define-variables-in-uniquely-named-json-a failed, reason: certificate has expired

**Comment by Fabbboy** [comment]
i also get "exports" and "require" is not defined

**Comment by hieunc229** [comment]
Welcome @Fabbby.

Those are Typescript's type errors (not something we can control), and you can ignore them. If the plugin doesn't work, it's likely that the installation was incorrect somewhere. Please check out @avangersKinkyClient video, step by step to install and fix certificate errors here https://youtu.be/crcpfLjNOgE

**Comment by Fabbboy** [comment]
It worked but after some time of testing i do not get more suggestions it dont react.

**Comment by hieunc229** [comment]
Interesting. When it doesn't show results, do you still have results for different keyword search? Or it's always have no results at all?

Would love to dig more into the issue

**Comment by Fabbboy** [comment]
nothing i dont get anything

**Comment by Fabbboy** [comment]
maybe there is something with my vsc insider because i reinstalled copilot-clone 2 times and it do not work im going to reinstall vsc insider

**Comment by hieunc229** [comment]
For sure. If the problem persist, let's have a chat over the discord DM! I'll try to see what's wrong.
