### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Gianiboy2265** [hieunc229/copilot-clone#52]
![Unbenannt](https://user-images.githubusercontent.com/86840255/148046002-6805741b-b3c6-4aa5-92e2-293a7f616f1e.PNG)

**Comment by Gianiboy2265** [comment]
Hey. I followed step by step the youtube video. And it started normally. But after I wanted to try the example find sentence or now a custom sentence there comes this error up.

**Comment by Gianiboy2265** [comment]
If you need any more things just let me know! :)
I hope you wirte back soon

**Comment by asim1425** [comment]
Try This: Work For Me (:
Add This Code: process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'; 
into line no 2 in src/utils/fetchPageContent.ts file
(Sorry For Bad English)

**Comment by Gianiboy2265** [comment]
hey I tried that and it worked for me. After 3 or 4 succesfull minutes. Capitain Stack doesn't find results anymore.

**Comment by Gianiboy2265** [comment]
![Unbenannt1](https://user-images.githubusercontent.com/86840255/148056473-2ee72653-7a08-4397-bb7e-788e261d3898.PNG)

**Comment by Gianiboy2265** [comment]
This is the only error for me atm

**Comment by asim1425** [comment]
Did You Run npm install ?

**Comment by Gianiboy2265** [comment]
yep

**Comment by Gianiboy2265** [comment]
I even re installed the whole thing

**Comment by Gianiboy2265** [comment]
and again the same issue

**Comment by asim1425** [comment]
Sorry, Idk About This Error

**Comment by hieunc229** [comment]
Hey @Gianiboy2265. 

It's Typescript errors. Different versions of Typescript might have different errors as well. 
Can you ignore the errors and start debugging?

**Comment by Gianiboy2265** [comment]
yes I can

**Comment by Gianiboy2265** [comment]
I just wondered bc when I first started the co-pilot the error wasn't there

**Comment by hieunc229** [comment]
When you install the dependencies, it'll download the latest `vscode-dts` automatically. It includes the definition for `vscode` module. The VSCode editor will start to read the type definition and through those errors.

Since the type definition for `vscode-dts` changes quite frequently (because Captain Stack uses an experimental API), updating code to fix those type errors will be outdated in a matter of weeks.

I'll close this thread since seems like the issue is resolved.

**Comment by hieunc229** [comment]
Duplicated of #45 and #48

**Comment by hieunc229** [comment]
Duplicate of #45 and #48

**Comment by hieunc229** [comment]
Duplicate of #45
