### ISSUE TITLE
Finished loading results but not showing

### ISSUE THREAD

**Issue by zendrix396** [hieunc229/copilot-clone#53]
![image](https://user-images.githubusercontent.com/71001844/150628359-a417127c-0ece-41b9-9042-b2407b24c883.png)

**Comment by free5ty1e** [comment]
I have this same issue.  iMac intel chipset running 11.6, visual code insiders.  Loads results according to the status bar but never shows them to me.

**Comment by free5ty1e** [comment]
how did you fix this?
