### ISSUE TITLE
Not showing any suggestions

### ISSUE THREAD

**Issue by GarvitCoder** [hieunc229/copilot-clone#55]
I installed Captain Stack like the video said. VS Code - Insider detects  some errors. Like this- 
![error](https://user-images.githubusercontent.com/88778635/158040146-0c6d9244-67a4-4577-bc62-94af49903a84.png)

When I run, it doesn't show any errors in the debug section nor terminal. It opens the window. But when I ask Captain Stack to do something it doesn't just anything. Thanks and have a great day!

**Comment by hieunc229** [comment]
Welcome, Gravit!

When the new window opened, did you try to enter the search query in that new window? Could you send me a screenshot of that new window, after typing the search query?

**Comment by GarvitCoder** [comment]
What query? You mean the comment code?

**Comment by GarvitCoder** [comment]
![not working](https://user-images.githubusercontent.com/88778635/158063614-895d4b96-0778-4d7b-a079-7c66e9868bd4.png)

**Comment by GarvitCoder** [comment]
I just found out. It also shows this in the terminal.
![wow](https://user-images.githubusercontent.com/88778635/158063693-d03b3d81-e4d5-4ff1-8d25-a5d99d7aa6bf.png)

**Comment by hieunc229** [comment]
You can ignore errors (as mentioned in #48).

Looks like the search query/comment you used missed a dot at the end. Try `//find random number javascript.` If the issue persist, let me know!

**Comment by GarvitCoder** [comment]
Thanks a lot! Hopefully, this program is way way underrated.

**Comment by GarvitCoder** [comment]
Thanks a lot! Hopefully, this program is way way underrated.

**Comment by hieunc229** [comment]
Thanks for your kind words Garvit.

Tagging other contributors to this program @clin1234 @Kek5chen @avangersGameDestruction
