### ISSUE TITLE
Finished loading results but never shows them

### ISSUE THREAD

**Issue by free5ty1e** [hieunc229/copilot-clone#61]
EDIT: This is in an Intel Mac running OSX 11.6

Freshly downloaded Visual Studio Code Insider today, followed instructions, ran extension, opened project in extension window, confirmed inline suggestions are enabled, attempted several search strings in a blank document and the suggestions never appear.  The status bar shows them loading and then shows captainstack finished loading xx results, but I never see the suggestions appear.  Someone else had this issue here but it was closed with no notes; how do I fix this? 

https://github.com/hieunc229/copilot-clone/issues/53

<img width="481" alt="Screen Shot 2022-05-16 at 12 29 18 PM" src="https://user-images.githubusercontent.com/5496151/168668015-d19f764f-0b41-41c6-8a94-2d5c142ab640.png">
<img width="516" alt="Screen Shot 2022-05-16 at 12 31 44 PM" src="https://user-images.githubusercontent.com/5496151/168668216-91aed143-7dfc-4d95-9d01-08aa9f520e2b.png">

**Comment by free5ty1e** [comment]
I followed the suggested video tutorial in Discord here https://www.youtube.com/watch?v=crcpfLjNOgE on a fresh Windows 10 v21H2 computer and got the exact same results.  CaptainStack: Finished loading XX results but nothing ever shows up as suggestions.  Confirmed the inline suggestion setting is checked as well as tried the `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` workaround in `src/utils/fetchPageContent.ts` on line 2, I never see any error notifications when I try to search, not sure how to proceed.  

I can provide any further troubleshooting information needed.  I've attached a more detailed screenshot showing both windows running on the mac
<img width="2531" alt="Screen Shot 2022-05-16 at 1 39 28 PM" src="https://user-images.githubusercontent.com/5496151/168710759-df0624cb-d94c-42e2-bddf-e62ea2f97055.png">

**Comment by free5ty1e** [comment]
The code structure so you can see I've got the root folder correct.  Trying to think of what else might be helpful to post, let me know if I can retrieve any info or logs or run commands to extract data for this.  Thank you!
<img width="1379" alt="Screen Shot 2022-05-16 at 6 49 59 PM" src="https://user-images.githubusercontent.com/5496151/168711895-d5aebf7b-023c-4062-8b15-d7cbc3e0f362.png">

**Comment by free5ty1e** [comment]
I forgot to mention the initial issue was seen on an Intel Mac running OSX 11.6, but it appears on a fresh Windows installation as well.  I've ensured I had all the prerequisites installed and working on both machines, such as npm, npx, git, etc... I made sure to install any dependencies that npm said were missing when I ran npm install, if any showed up.

**Comment by Kek5chen** [comment]
I have tested this myself, it is definitely not working. It compiles to my surprise, but it does not do anything except say that the results loaded.

From testing I think that the problem lies in the usage of the new update of vs code insiders. They most likely changed something the postinstall script needs. @hieunc229 that was your part and it would be nice if you could check it out.

**Comment by Kek5chen** [comment]
it should still work fine on older versions of vs code is my guess.

**Comment by free5ty1e** [comment]
aha, that's a good thought!  I'll look into how to get my hands on an older vs code insider.  Or will this work on plain vs code of a certain version?  That will work just fine for me for the moment, I don't need the latest for any other reason :)

**Comment by Kek5chen** [comment]
It will not work on the stable branch of vscode since the inlineCompletions feature is part of the proposed API of the insider versions.

**Comment by hieunc229** [comment]
This bug was caused by the [recent changes from the VSCode official API](https://github.com/microsoft/vscode-extension-samples/commit/ec0c17a621e523fc9b2c999ca778c8059e077a37). I [made an update](https://github.com/hieunc229/copilot-clone/commit/59a0146263815c97d3d9891ef062d0d58229724e) that should fix this issue.

Feel free to reopen or open a new thread for further discussion
