### ISSUE TITLE
Port From Insider To Stable VS Code

### ISSUE THREAD

**Issue by dgbkn** [hieunc229/copilot-clone#62]
The proposed API for inline completions has now been released.

See this:
https://github.com/microsoft/vscode-discussions/discussions/26

**Comment by hieunc229** [comment]
Thanks for the notice. We'll work on publishing it

**Comment by Kek5chen** [comment]
@hieunc229 I created a `port-proposed-api` branch to link future pull requests automatically. make sure to continue development in there.

**Comment by dgbkn** [comment]
@hieunc229 any updates?

**Comment by hieunc229** [comment]
Hey @dgbkn, we published the extension last week. You can find "Captain Stack" on VSCode Marketplace, or using this link https://marketplace.visualstudio.com/items?itemName=captainstack.captain-stack

My apology, I haven't made an update as my schedule is packed recently.

Any feedback are welcome and if you like it, would appreciate your rating on the marketplace!

**Comment by Kek5chen** [comment]
Wrongfully closed as Captain Stack hasn't been ported from insider yet.

**Comment by dgbkn** [comment]
@hieunc229 Thanks , @Kek5chen - He Has Added to VS Code See ScreenShot
![image](https://user-images.githubusercontent.com/65810521/176830688-dd071ab0-2176-45e1-a545-72e18f9de294.png)

**Comment by dgbkn** [comment]
![image](https://user-images.githubusercontent.com/65810521/176830751-b5e0b775-7cf2-4a7f-9898-1b8c9f4ea16f.png)
Thanks For Your Work

**Comment by Kek5chen** [comment]
Still an issue as Captain Stack has not yet ported to stable vs code.

Will be resolved with #65
