### ISSUE TITLE
Publish to OpenVSX registry?

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#66]
Now that #62 is done, maybe revisit #11?

**Comment by Kek5chen** [comment]
Is that still relevant now that we are in the official VS Marketplace?

**Comment by clin1234** [comment]
Useful for VSCodium users, who can't access the official marketplace, without significant effort.
________________________________

**Comment by Kek5chen** [comment]
Okay. Since this is still relevant then we will have a look into publishing
it there too. Thanks for bringing this up.

**Comment by hieunc229** [comment]
I think we'll do it when the actual users request to publish on the OpenVSX registry.

I'll close this thread for now.
