### ISSUE TITLE
FetchError

### ISSUE THREAD

**Issue by fadelmaulana** [hieunc229/copilot-clone#68]
FetchError Request while push a request on visual studio code
![image](https://user-images.githubusercontent.com/41320138/184015417-c91608d0-f239-439a-946b-0d78d273aa1f.png)
![image](https://user-images.githubusercontent.com/41320138/184015489-fda0bb62-9f01-4b88-b038-788936fa0788.png)

**Comment by hieunc229** [comment]
Welcome @fadelmaulana, I suspect your IP might be blacklisted by StackOverflow. 
Have you been using the extension before getting the error, or is it on the first try?
