### ISSUE TITLE
Lets on Extentions like Co-Pilot

### ISSUE THREAD

**Issue by ghost** [hieunc229/copilot-clone#70]
Type: <b>Feature Request</b>

like to use more ext like co-pilot and captainStack(free). Thank You.

Extension version: 0.0.6
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by hieunc229** [comment]
Hi @nurulalamrony, I'm glad that you enjoy using it. Is there any feature request would you like to to see for Captain Stack?

**Comment by Kek5chen** [comment]
Closed due to lack of information and inactivity.
