### ISSUE TITLE
sending a request for a custom server

### ISSUE THREAD

**Issue by anwarzalek** [hieunc229/copilot-clone#71]
i want to host a ai code completion model on my local machine and i want to make the extension to send the query to that api instead of sending it to google or stackoverflow
can you please add to doc how can i customize the URL that the request will be sent to?
and for the query that has to be sent,  how can i customize it?

**Comment by Kek5chen** [comment]
For that you can just add a new extractor. If you are unsure on how to use them, have a look at the existing ones.

The gist one is the most simple to understand I would say:
https://github.com/hieunc229/copilot-clone/blob/master/src/utils/extractors/ExtractorGithubGist.ts

The base of what you need for a new extractor basically is:
```js
import ExtractorAbstract, { SnippetResult } from "./ExtractorAbstract";

export default class ExtractorImpl extends ExtractorAbstract {
    extractSnippets = (options: FetchPageResult): SnippetResult[] => {
        const item: SnippetResult = {
            votes: 0, // if applies, otherwise just leave at 0
            code: "",
            sourceURL: options.url,
            hasCheckMark: false // if applies and answer is marked as solution, otherwise just false
        };
        return [item];
    };
}
```

**Comment by Kek5chen** [comment]
I don't think documentation would be necessary, nor in the right place. If similar issues appear in the future, I think it would be proper to handle it by referencing this solution.
