### ISSUE TITLE
Cant See Finished and Loaded Results with Inline Suggest

### ISSUE THREAD

**Issue by ErdemOzgen** [hieunc229/copilot-clone#77]
CaptainStack has been find code and tells in status bar but can see inline suggest.
![Screenshot from 2022-11-20 23-02-12](https://user-images.githubusercontent.com/14043035/202923623-b9e641ea-b032-48e1-bf23-ddd848433898.png)

Also :
* Make sure Inline Suggest is enabled from the VS Code Settings ==> Enabled

**VSCODE**
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-03T14:04:08.642Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.78-1-MANJARO
Sandboxed: No

**Comment by reidsneo** [comment]
How to use

**To trigger inline completion, you'll need to type //find {your keyword}. (start with //find, end with a dot .)**

For example

`//find binary search in javascript.`

your are missing dot in the ending of query
