### ISSUE TITLE
Extension "enable-proposed-api" error.

### ISSUE THREAD

**Issue by therealOri** [hieunc229/copilot-clone#78]
Well, I decided to give this extension a try, I am using VSCodium not VS Code. And the extension keeps giving me the follwoing error message.

```bash
editor/inlineCompletions/actions is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["inlineCompletionsAdditions"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api captain-stack.captain-stack
```

Now, I did go looking through the closed Issues and found one that looked like they were having the same issue. [Here](https://github.com/hieunc229/copilot-clone/issues/8)

The issue I have is that I don't have a directory called `.vscode`, but instead `.vscode-oss`. There also is no "launch.json" file anywhere in this directory or any sub directories. Making one and copy/pasting the code provided in the issue I mentioned also doesn't seem to have any affect.

I was wondering if anyone had any other ideas?
__ __

<br />
<br />

Extra info.
I am using Manjaro Linux.
I installed the following from the AUR.
* http://aur.archlinux.org/packages/vscodium-bin
* https://github.com/VSCodium/vscodium

**Comment by hieunc229** [comment]
Hi @therealOri, thanks for the bug report. We haven't update the extension on VSCodium. Since then, the `inlineCompletionsAdditions` is official and no longer a proposed api (hence the error)

I'll spend some time updating the extension on VSCodium and get back to you

**Comment by hieunc229** [comment]
Close this thread since we'll only focus on VSCode marketplace
