### ISSUE TITLE
Support for VSCodium?

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#8]
While VSCodium does not have an Insiders build, it does support inline-completion (editor.inlineSuggest.enabled). However, attempting to run the extension results in an error:

`[hieunc229.copilot-clone]: editor/inlineCompletions/actions is a proposed menu identifier and is only available when running out of dev or with the following command line switch: --enable-proposed-api hieunc229.copilot-clone`

![image](https://user-images.githubusercontent.com/39310467/126180487-4785831b-af30-4271-ac9c-c1d1c7dad6a6.png)
![image](https://user-images.githubusercontent.com/39310467/126180629-d5cb7e16-8a44-4178-bd89-f885caa0dbab.png)

**Comment by hieunc229** [comment]
I tested it on VSCodium and it works.

But it needs to have `--enable-proposed-api` argument. You can:

1. Open the file `.vscode/launch.json`
2. Append `--enable-proposed-api` into "configurations.args" string array

_It should looks something like this_
```js
{
	...
	"configurations": [{
			...
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--enable-proposed-api"
			],
			...
		}
	]
}
```

And don't forget to enable inline completion.

**Comment by clin1234** [comment]
Still got the above error, even with inline completion on.

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--enable-proposed-api hieunc229.copilot-clone"
			],
        }
    ]
}
```

**Comment by hieunc229** [comment]
That configuration is different from the one in this repository. You can have a look here: https://github.com/hieunc229/copilot-clone/blob/master/.vscode/launch.json

Below is what it should look like.

```json
{
	"version": "0.2.0",
	"configurations": [{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--enable-proposed-api"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "npm: watch"
		}
	]
}
```

What does that `python` configure do?

**Comment by clin1234** [comment]
Issue solved.
