### ISSUE TITLE
Always get "Finished loading 0 results"

### ISSUE THREAD

**Issue by tanc** [hieunc229/copilot-clone#81]
I'm interested in trying this extension but I'm having trouble getting any results.

I'm in a PHP file and trying various queries like:

```
//find php generate random number.
```
or
```
//find drupal create term.
```

But I always get the following in the toolbar:
```
CaptainStack: Finished loading 0 results
```

Is there something I'm doing wrong? How can I help debug the problem?

https://user-images.githubusercontent.com/76320/231973129-5b9f6f41-1171-4423-860c-79f7104b2a69.mp4

**Comment by fabrizio1924** [comment]
Hi! have you solved it?
I have the same problem, I have tried it on two computers and can't find results.

**Comment by hieunc229** [comment]
Sorry for the late reply @tanc, Did you enable any provider? (Github Gist, StackOverflow, now have OpenAI and OpenRouter)
