### ISSUE TITLE
Support for HTML & CSS

### ISSUE THREAD

**Issue by freelancernik** [hieunc229/copilot-clone#84]
To trigger inline completion, you'll need to type //find {your keyword}. (start with //find, end with a dot .)

but the comments in HTML & CSS don't start with //
Can you please support HTML & CSS?

**Comment by hieunc229** [comment]
Hi @freelancernik, let me have a look and make an update

**Comment by hieunc229** [comment]
Close this thread since `<!--` (HTML) is already supported, and `/*` is supported in v0.6.0 recent update
