### ISSUE TITLE
Incorrect `match` in the source code results in inaccurate matching results.I don't know if this is a bug...

### ISSUE THREAD

**Issue by mengyangz86** [hieunc229/copilot-clone#88]
this code `const [_, commentSyntax, searchPhrase, commentSyntaxEnd] = match;` in `matchSearchPhrase.ts` 。The suggestions for this extension are as follows: 
![image](https://github.com/user-attachments/assets/b1c4de17-f275-4dc1-88ee-02ada0ab6978)

The result obtained by the regular expression is 4 groups. In addition to the first item, there should be 4 items in the match to fully indicate it. The `searchPhrase` in the source code only represents `find`, not `find {question}`, so one item should be added, as shown below:
`const [_, commentSyntax, searchSymbol, searchPhrase, commentSyntaxEnd] = match;`，The output after debugging is as follows:
![image](https://github.com/user-attachments/assets/27811dfa-e789-47d7-a02d-ec38618e4f6a)
After the modification, the result of debugging this extension is as follows:
![image](https://github.com/user-attachments/assets/db135da8-38b8-42e9-a0a9-b3fb621095ab)

**Comment by hieunc229** [comment]
You're right. I've pushed an update for this issue https://github.com/hieunc229/copilot-clone/commit/1edf91fd0b8dcfcf4b27a4d2a6d86d5c8e865de7 and will make an update to the extension marketplace

Thanks for spotting it @mengyangz86
