### ISSUE TITLE
canvas.node was compiled against a different Node.js version

### ISSUE THREAD

**Issue by aqgasa** [hieunc229/copilot-clone#9]
I get the following error: "Activating extension 'hieunc229.copilot-clone' failed: The module '/Users/[USER]/captain-stack/node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 89. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)"

I tried re-compiling with the latest node.js version which was NODE_MODULE_VERSION 93.
There is no NODE_MODULE_VERSION 89 on page https://nodejs.org/en/download/releases/
Which node.js version do you use that is NODE_MODULE_VERSION 89 ?

Thank you!

**Comment by hieunc229** [comment]
My NODE_MODULE_VERSION is 83 (v14.1.0).

Can you try to remove the `node_modules` and reinstall it (by running `npm install` command)?
https://github.com/Automattic/node-canvas/issues/1498

**Comment by aqgasa** [comment]
Thank you for answering. Reinstalling did not help. But when I removed canvas module (npm uninstall canvas --save) it seems to work just fine.

**Comment by hieunc229** [comment]
Seems like canvas is out-of-date. Thanks for the info @aqgasa. I'll make some changes
